import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/component/header/Header";
import Footer from "@/component/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <header>
            <Header />
          </header>
          <main className="flex-grow">{children}</main>
          <footer className="bg-slate-800 py-4 fixed bottom-0 w-full text-center text-white">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
